name: Evidence 4 Faith
favicon: null
layout_spectrum: 0.05176968686282635
typography_spectrum: 0.005651097046211362
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.1792683801613748
  lightness: 0.624198785983026
  saturation: 0.8973186099901795
  rhythmicContrast: 0.6895009137224406
purpose: []
